apiVersion: apps/v1
kind: Deployment
metadata:
 name: globoapp-deployment
 labels:
   app: globoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globoapp
  template:
    metadata:
      labels:
        app: globoapp
    spec:
     containers:
     - name: globoapp
       image: 036240555793.dkr.ecr.us-east-1.amazonaws.com/globoapp
       ports:
       - containerPort: 3000